import type { AgentRunner, AgentRunResult, AgentRunSpec } from './runner.js';

export type StageFixture = (spec: AgentRunSpec) => unknown;

/**
 * Deterministic runner: no API calls, no credentials, no tokens.
 *
 * Every pipeline test in this repo runs against it, and `--dry-run` exercises
 * the whole flow end to end. Pipelines that can only be tested with a live
 * model are pipelines that do not get tested.
 */
export class DryRunAgentRunner implements AgentRunner {
  readonly calls: AgentRunSpec[] = [];

  constructor(private readonly fixtures: Record<string, StageFixture> = {}) {}

  async run<T = unknown>(spec: AgentRunSpec): Promise<AgentRunResult<T>> {
    this.calls.push(spec);
    const fixture = this.fixtures[spec.stage] ?? defaultFixtures[spec.stage];
    const value = fixture ? fixture(spec) : { note: `no fixture for stage ${spec.stage}` };

    // Validate the fixture against the real schema, so a stage whose schema
    // changes without its fixture fails loudly in tests.
    let data = value as T;
    let error: string | null = null;
    if (spec.schema) {
      const parsed = spec.schema.safeParse(value);
      if (parsed.success) data = parsed.data as T;
      else error = parsed.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ');
    }

    return {
      ok: error === null,
      data: error === null ? data : null,
      text: JSON.stringify(value),
      costUsd: 0,
      inputTokens: 0,
      outputTokens: 0,
      durationMs: 0,
      turns: 1,
      denials: [],
      error,
    };
  }
}

/**
 * Fixtures that satisfy every stage schema, so `--dry-run` produces a complete,
 * inspectable run without a single API call.
 */
export const defaultFixtures: Record<string, StageFixture> = {
  triage: () => ({
    actionable: true,
    reason: 'Describes a concrete behaviour change in a known repository.',
    repo: 'demo-service',
    repoResolvedBy: 'area-mapping',
    confidence: 0.82,
  }),

  analyze: () => ({
    restatement: 'Add an idempotency key to the refund endpoint so retried requests do not double-refund.',
    inScopeBehaviour: [
      'Accept a client-supplied idempotency key on the refund request',
      'A repeated key returns the original refund without a second charge',
    ],
    outOfScope: ['Backfilling idempotency keys onto historical refunds'],
    assumptions: [
      { assumption: 'Keys are client-generated UUIDs', basis: 'work item comment #4', risk: 'low' },
    ],
    openQuestions: [],
    affectedAreas: [
      { path: 'src/refunds/service.ts', why: 'Refund write path', confidence: 0.9 },
      { path: 'src/refunds/repository.ts', why: 'Needs the unique index and conflict handling', confidence: 0.8 },
    ],
    existingCoverage: {
      hasTests: true,
      testFiles: ['src/refunds/service.test.ts'],
      gap: 'No test constructs a refund through the import path',
    },
    risk: { level: 'medium', factors: ['Touches the refund write path', 'Requires a migration'] },
  }),

  plan: (spec) => ({
    understanding: 'Retried refund requests currently create duplicate refunds.',
    approach: 'Store a client-supplied idempotency key with a unique index; a repeat key returns the original refund.',
    rejectedAlternative: 'Server-side hash of the payload — breaks legitimate retries with a changed reason string.',
    changes: [
      { file: 'src/refunds/service.ts', change: 'Thread the idempotency key through to the repository', why: 'Requirement 1' },
      { file: 'src/refunds/repository.ts', change: 'Unique index plus conflict handling', why: 'Prevents double-refund' },
    ],
    tests: [
      'Duplicate key returns the original refund and does not charge twice',
      'Missing key returns 400 using the existing error contract',
    ],
    assumptions: [
      { assumption: 'Keys are client-generated UUIDs', basis: 'work item comment #4', risk: 'low' },
    ],
    risk: { level: 'medium', factors: ['Refund write path', 'Additive migration'] },
    blastRadius: {
      filesChanged: 4,
      linesChanged: 120,
      publicApiChange: false,
      schemaChange: true,
      configChange: false,
      deployOrderNote: 'Migration must be deployed before the application',
    },
    outOfScope: ['Backfilling historical refunds'],
    rollback: 'Revert the merge request; the migration is additive and safe to leave in place.',
    markdown: `## Plan (dry run)\n\nGenerated by DryRunAgentRunner for stage "${spec.stage}".`,
  }),

  rootCause: () => ({
    hypothesis: 'The refund service dereferences payment metadata that the import path never sets.',
    evidenceChain: [
      { claim: 'Throws at src/refunds/service.ts:142', evidence: 'stack frame present in all samples' },
      { claim: 'Metadata is unset on the import path', evidence: 'src/imports/payment-importer.ts:88' },
    ],
    confidence: 0.86,
    alternativeHypotheses: [
      { hypothesis: 'Concurrent mutation clears the metadata', whyLessLikely: 'No writers found on that field' },
    ],
    category: 'defensive',
    severity: 'high',
    reproduction: 'Refund a payment created through the import path.',
    whyTestsMissedIt: 'Existing tests construct payments through the API path only.',
    notACodeIssue: false,
  }),

  implement: () => ({
    status: 'complete',
    summary: 'Added the idempotency key end to end, with a unique index and conflict handling.',
    deviations: [],
    observations: ['The import path has no test fixture; worth filing separately.'],
    commits: ['feat(refunds): accept an idempotency key', 'test(refunds): cover duplicate keys'],
    filesChanged: ['src/refunds/service.ts', 'src/refunds/repository.ts', 'src/refunds/service.test.ts'],
    linesChanged: 118,
  }),

  verify: () => ({
    findings: [],
    planConformance: { followed: true, missing: [], extra: [] },
    verdict: 'ready',
  }),

  publish: () => 'Dry-run merge request description.',
};
